import { dir } from 'i18next';
import { MdArrowBack } from 'react-icons/md';
import { languages } from '../../i18n/settings';
import { ParamsLng } from '@/types';

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: 'Resume portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: ParamsLng;
}) {
  return (
    <>
      {/* <header className="w-screen h-[20%]">
        <MdArrowBack className="icon-card-home" />
      </header> */}
      {children}
    </>
  );
}
