import './globals.css';
import { dir } from 'i18next';
import { languages } from '../i18n/settings';
import { ParamsLng } from '@/types';
import MyLinks from './components/MyLinks';
import { Poppins } from '@next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: "Edoardo's portfolio",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: ParamsLng;
}) {
  return (
    <html lang={lng} dir={dir(lng)} className={poppins.className}>
      <head />
      <body className="bg-bgPrimary text-textPrimary">
        <MyLinks />
        <main className=" mx-3 ">{children}</main>
      </body>
    </html>
  );
}
